"""
Streamlit dashboard for the Digital Commerce Performance Dashboard.
Reads the CSV exports in data/powerbi/ generated by `python main.py`.
"""
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from pathlib import Path

st.set_page_config(
    page_title="Digital Commerce Dashboard",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)

DATA = Path("data/powerbi")

PALETTE = {
    "blue":   "#2980B9",
    "green":  "#1E8449",
    "purple": "#8E44AD",
    "red":    "#C0392B",
    "orange": "#E67E22",
}


@st.cache_data
def load():
    return {
        "orders":   pd.read_csv(DATA / "fact_orders.csv",
                                parse_dates=["order_date", "week_start"]),
        "weekly":   pd.read_csv(DATA / "weekly_kpis.csv",
                                parse_dates=["week_start"]),
        "forecast": pd.read_csv(DATA / "sales_forecast.csv",
                                parse_dates=["week_start"]),
        "churn":    pd.read_csv(DATA / "customer_churn_risk.csv"),
        "demand":   pd.read_csv(DATA / "product_demand_predictions.csv",
                                parse_dates=["week"]),
    }


data = load()

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("Digital Commerce")
    page = st.radio(
        "Navigate",
        ["Executive Overview", "Predictive Insights"],
        label_visibility="collapsed",
    )
    st.divider()
    years = sorted(data["orders"]["order_date"].dt.year.unique())
    sel_years = st.multiselect("Filter by year", years, default=years)

if not sel_years:
    st.warning("Select at least one year in the sidebar.")
    st.stop()

# ── Filtered slices ───────────────────────────────────────────────────────────
orders    = data["orders"][data["orders"]["order_date"].dt.year.isin(sel_years)]
completed = orders[orders["is_completed"] == True]
weekly    = data["weekly"][data["weekly"]["week_start"].dt.year.isin(sel_years)]


def _gbp(v: float) -> str:
    if v >= 1_000_000:
        return f"£{v / 1_000_000:.1f}M"
    if v >= 1_000:
        return f"£{v / 1_000:.0f}K"
    return f"£{v:.0f}"


def _pct(v: float) -> str:
    return f"{v * 100:.1f}%"


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PAGE 1 — EXECUTIVE OVERVIEW
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
if page == "Executive Overview":
    st.header("Executive Overview")

    total_rev   = completed["revenue"].sum()
    total_ord   = len(completed)
    aov         = total_rev / total_ord if total_ord else 0
    gm_pct      = completed["margin"].sum() / total_rev if total_rev else 0
    active_cust = completed["customer_id"].nunique()

    last = weekly.sort_values("week_start").iloc[-1] if len(weekly) > 1 else None
    rev_delta = (
        f"{last['revenue_wow_growth'] * 100:+.1f}% WoW"
        if last is not None and pd.notna(last["revenue_wow_growth"])
        else None
    )
    ord_delta = (
        f"{last['orders_wow_growth'] * 100:+.1f}% WoW"
        if last is not None and pd.notna(last["orders_wow_growth"])
        else None
    )

    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Total Revenue",    _gbp(total_rev),   delta=rev_delta)
    c2.metric("Total Orders",     f"{total_ord:,}",   delta=ord_delta)
    c3.metric("Avg Order Value",  _gbp(aov))
    c4.metric("Gross Margin",     _pct(gm_pct))
    c5.metric("Active Customers", f"{active_cust:,}")

    st.divider()

    fig = px.area(
        weekly.sort_values("week_start"),
        x="week_start", y="total_revenue",
        title="Weekly Revenue",
        labels={"week_start": "", "total_revenue": "Revenue (£)"},
        color_discrete_sequence=[PALETTE["blue"]],
    )
    fig.update_traces(fillcolor="rgba(41,128,185,0.12)", line_color=PALETTE["blue"])
    fig.update_layout(hovermode="x unified", showlegend=False)
    st.plotly_chart(fig, use_container_width=True)

    col1, col2 = st.columns(2)

    with col1:
        seg = (
            completed.groupby("customer_segment")["revenue"]
            .sum().reset_index()
            .rename(columns={"revenue": "total_revenue"})
            .sort_values("total_revenue")
        )
        fig = px.bar(
            seg, x="total_revenue", y="customer_segment", orientation="h",
            title="Revenue by Customer Segment",
            labels={"total_revenue": "Revenue (£)", "customer_segment": ""},
            color_discrete_sequence=[PALETTE["green"]],
        )
        fig.update_layout(showlegend=False)
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        ch = (
            completed.groupby("sales_channel")["revenue"]
            .sum().reset_index()
            .rename(columns={"revenue": "total_revenue"})
            .sort_values("total_revenue")
        )
        fig = px.bar(
            ch, x="total_revenue", y="sales_channel", orientation="h",
            title="Revenue by Sales Channel",
            labels={"total_revenue": "Revenue (£)", "sales_channel": ""},
            color_discrete_sequence=[PALETTE["blue"]],
        )
        fig.update_layout(showlegend=False)
        st.plotly_chart(fig, use_container_width=True)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# PAGE 2 — PREDICTIVE INSIGHTS
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
else:
    st.header("Predictive Insights")

    forecast = data["forecast"].copy()
    actuals  = forecast[forecast["is_future"] == False]
    future   = forecast[forecast["is_future"] == True]

    pred_rev  = future["predicted_revenue"].sum()
    high_risk = (data["churn"]["risk_level"] == "High").sum()
    churn_rate = high_risk / len(data["churn"])

    c1, c2 = st.columns(2)
    c1.metric("Predicted Revenue (next 4 weeks)", _gbp(pred_rev))
    c2.metric(
        "High Churn Risk Customers",
        f"{high_risk:,}",
        delta=f"{churn_rate * 100:.0f}% of customer base",
        delta_color="inverse",
    )

    st.divider()

    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=actuals["week_start"], y=actuals["actual_revenue"],
        name="Actual", line=dict(color=PALETTE["blue"], width=2),
    ))
    fig.add_trace(go.Scatter(
        x=actuals["week_start"], y=actuals["predicted_revenue"],
        name="Predicted (in-sample)",
        line=dict(color=PALETTE["green"], dash="dot", width=1.5),
    ))
    fig.add_trace(go.Bar(
        x=future["week_start"], y=future["predicted_revenue"],
        name="Forecast (next 4 weeks)",
        marker_color=PALETTE["purple"], opacity=0.85,
    ))
    fig.update_layout(
        title="Revenue Forecast",
        hovermode="x unified",
        xaxis_title="", yaxis_title="Revenue (£)",
        legend=dict(orientation="h", yanchor="bottom", y=1.02),
    )
    st.plotly_chart(fig, use_container_width=True)

    col1, col2 = st.columns(2)

    with col1:
        risk_counts = (
            data["churn"]["risk_level"]
            .value_counts()
            .reindex(["Low", "Medium", "High"])
            .reset_index()
        )
        risk_counts.columns = ["risk_level", "count"]
        fig = px.bar(
            risk_counts, x="risk_level", y="count",
            title="Customer Churn Risk Distribution",
            labels={"risk_level": "Risk Level", "count": "Customers"},
            color="risk_level",
            color_discrete_map={
                "Low":    PALETTE["green"],
                "Medium": PALETTE["orange"],
                "High":   PALETTE["red"],
            },
        )
        fig.update_layout(showlegend=False)
        st.plotly_chart(fig, use_container_width=True)

    with col2:
        demand = data["demand"].copy()
        latest = (
            demand.sort_values("week")
            .groupby("product_category")
            .last()
            .reset_index()
            .sort_values("actual_units_sold")
        )
        fig = px.bar(
            latest,
            x="actual_units_sold", y="product_category", orientation="h",
            title="Units Sold by Category (Latest Week)",
            labels={"actual_units_sold": "Units Sold", "product_category": ""},
            color="demand_trend",
            color_discrete_map={
                "Increasing": PALETTE["green"],
                "Stable":     PALETTE["blue"],
                "Decreasing": PALETTE["red"],
            },
        )
        st.plotly_chart(fig, use_container_width=True)
