table dim_customers

	column customer_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: customer_id

	column customer_segment
		dataType: string
		summarizeBy: none
		sourceColumn: customer_segment

	column city
		dataType: string
		summarizeBy: none
		sourceColumn: city

	column customer_signup_date
		dataType: dateTime
		formatString: Short Date
		summarizeBy: none
		sourceColumn: customer_signup_date

	column days_since_last_purchase
		dataType: int64
		summarizeBy: average
		sourceColumn: days_since_last_purchase

	column purchase_frequency
		dataType: int64
		summarizeBy: sum
		sourceColumn: purchase_frequency

	column total_revenue
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: total_revenue

	column avg_order_value
		dataType: double
		formatString: #,0.00
		summarizeBy: average
		sourceColumn: avg_order_value

	column is_repeat_customer
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_repeat_customer

	column is_churned
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_churned

	partition dim_customers-dim_customers = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents(DataFolderPath & "dim_customers.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"customer_id", type text},
				        {"customer_segment", type text},
				        {"city", type text},
				        {"customer_signup_date", type date},
				        {"days_since_last_purchase", Int64.Type},
				        {"purchase_frequency", Int64.Type},
				        {"total_revenue", type number},
				        {"avg_order_value", type number},
				        {"is_repeat_customer", type logical},
				        {"is_churned", type logical}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

