table dim_products

	column product_id
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: product_id

	column product_name
		dataType: string
		summarizeBy: none
		sourceColumn: product_name

	column product_category
		dataType: string
		summarizeBy: none
		sourceColumn: product_category

	column unit_price
		dataType: double
		formatString: #,0.00
		summarizeBy: average
		sourceColumn: unit_price

	partition dim_products-dim_products = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents(DataFolderPath & "dim_products.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"product_id", type text},
				        {"product_name", type text},
				        {"product_category", type text},
				        {"unit_price", type number}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

