table fact_orders

	column order_id
		dataType: string
		summarizeBy: none
		sourceColumn: order_id

	column order_date
		dataType: dateTime
		summarizeBy: none
		sourceColumn: order_date
		formatString: Short Date

	column week_start
		dataType: dateTime
		summarizeBy: none
		sourceColumn: week_start
		formatString: Short Date

	column year
		dataType: int64
		summarizeBy: none
		sourceColumn: year

	column month
		dataType: int64
		summarizeBy: none
		sourceColumn: month

	column week_number
		dataType: int64
		summarizeBy: none
		sourceColumn: week_number

	column quarter
		dataType: int64
		summarizeBy: none
		sourceColumn: quarter

	column customer_id
		dataType: string
		summarizeBy: none
		sourceColumn: customer_id

	column customer_segment
		dataType: string
		summarizeBy: none
		sourceColumn: customer_segment

	column product_id
		dataType: string
		summarizeBy: none
		sourceColumn: product_id

	column product_category
		dataType: string
		summarizeBy: none
		sourceColumn: product_category

	column product_name
		dataType: string
		summarizeBy: none
		sourceColumn: product_name

	column quantity
		dataType: int64
		summarizeBy: sum
		sourceColumn: quantity

	column unit_price
		dataType: double
		summarizeBy: none
		sourceColumn: unit_price
		formatString: #,0.00

	column discount
		dataType: double
		summarizeBy: average
		sourceColumn: discount
		formatString: 0.00%

	column revenue
		dataType: double
		summarizeBy: sum
		sourceColumn: revenue
		formatString: #,0.00

	column margin
		dataType: double
		summarizeBy: sum
		sourceColumn: margin
		formatString: #,0.00

	column city
		dataType: string
		summarizeBy: none
		sourceColumn: city

	column sales_channel
		dataType: string
		summarizeBy: none
		sourceColumn: sales_channel

	column campaign_name
		dataType: string
		summarizeBy: none
		sourceColumn: campaign_name

	column visits
		dataType: int64
		summarizeBy: sum
		sourceColumn: visits

	column cart_additions
		dataType: int64
		summarizeBy: sum
		sourceColumn: cart_additions

	column completed_orders
		dataType: int64
		summarizeBy: sum
		sourceColumn: completed_orders

	column payment_method
		dataType: string
		summarizeBy: none
		sourceColumn: payment_method

	column order_status
		dataType: string
		summarizeBy: none
		sourceColumn: order_status

	column is_completed
		dataType: boolean
		summarizeBy: none
		sourceColumn: is_completed

	column conversion_rate
		dataType: double
		summarizeBy: average
		sourceColumn: conversion_rate
		formatString: 0.00%

	column cart_abandonment_rate
		dataType: double
		summarizeBy: average
		sourceColumn: cart_abandonment_rate
		formatString: 0.00%

	partition fact_orders-fact_orders = m
		mode: import
		source =
			let
			    Source = Csv.Document(
			        File.Contents(DataFolderPath & "fact_orders.csv"),
			        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
			    ),
			    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
			        {"order_id", type text},
			        {"order_date", type date},
			        {"week_start", type date},
			        {"year", Int64.Type},
			        {"month", Int64.Type},
			        {"week_number", Int64.Type},
			        {"quarter", Int64.Type},
			        {"customer_id", type text},
			        {"customer_segment", type text},
			        {"product_id", type text},
			        {"product_category", type text},
			        {"product_name", type text},
			        {"quantity", Int64.Type},
			        {"unit_price", type number},
			        {"discount", type number},
			        {"revenue", type number},
			        {"margin", type number},
			        {"city", type text},
			        {"sales_channel", type text},
			        {"campaign_name", type text},
			        {"visits", Int64.Type},
			        {"cart_additions", Int64.Type},
			        {"completed_orders", Int64.Type},
			        {"payment_method", type text},
			        {"order_status", type text},
			        {"is_completed", type logical},
			        {"conversion_rate", type number},
			        {"cart_abandonment_rate", type number}
			    })
			in
			    #"Changed Type"

	annotation PBI_ResultType = Table
