table model_performance

	column model
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: model

	column algorithm
		dataType: string
		summarizeBy: none
		sourceColumn: algorithm

	column target
		dataType: string
		summarizeBy: none
		sourceColumn: target

	column metric_type
		dataType: string
		summarizeBy: none
		sourceColumn: metric_type

	column MAE
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: MAE

	column RMSE
		dataType: double
		formatString: #,0.00
		summarizeBy: none
		sourceColumn: RMSE

	column MAPE_pct
		dataType: double
		formatString: 0.00
		summarizeBy: none
		sourceColumn: MAPE_pct

	column Accuracy
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: Accuracy

	column F1
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: F1

	column ROC_AUC
		dataType: double
		formatString: 0.0000
		summarizeBy: none
		sourceColumn: ROC_AUC

	partition model_performance-model_performance = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents(DataFolderPath & "model_performance.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"model", type text},
				        {"algorithm", type text},
				        {"target", type text},
				        {"metric_type", type text},
				        {"MAE", type number},
				        {"RMSE", type number},
				        {"MAPE_pct", type number},
				        {"Accuracy", type number},
				        {"F1", type number},
				        {"ROC_AUC", type number}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

