table sales_forecast

	column week_start
		dataType: dateTime
		isKey
		summarizeBy: none
		sourceColumn: week_start
		formatString: Short Date

	column actual_revenue
		dataType: double
		summarizeBy: sum
		sourceColumn: actual_revenue
		formatString: #,0.00

	column predicted_revenue
		dataType: double
		summarizeBy: sum
		sourceColumn: predicted_revenue
		formatString: #,0.00

	column prediction_error
		dataType: double
		summarizeBy: sum
		sourceColumn: prediction_error
		formatString: #,0.00

	column model_name
		dataType: string
		summarizeBy: none
		sourceColumn: model_name

	partition sales_forecast-sales_forecast = m
		mode: import
		source =
			let
			    Source = Csv.Document(
			        File.Contents(DataFolderPath & "sales_forecast.csv"),
			        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
			    ),
			    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
			        {"week_start", type date},
			        {"actual_revenue", type number},
			        {"predicted_revenue", type number},
			        {"prediction_error", type number},
			        {"model_name", type text}
			    })
			in
			    #"Changed Type"

	annotation PBI_ResultType = Table
