table segment_performance

	column customer_segment
		dataType: string
		isKey
		summarizeBy: none
		sourceColumn: customer_segment

	column total_revenue
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: total_revenue

	column total_orders
		dataType: int64
		summarizeBy: sum
		sourceColumn: total_orders

	column unique_customers
		dataType: int64
		summarizeBy: sum
		sourceColumn: unique_customers

	column avg_order_value
		dataType: double
		formatString: #,0.00
		summarizeBy: average
		sourceColumn: avg_order_value

	column total_margin
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: total_margin

	column repeat_customers
		dataType: double
		summarizeBy: sum
		sourceColumn: repeat_customers

	column gross_margin_pct
		dataType: double
		formatString: 0.00%
		summarizeBy: average
		sourceColumn: gross_margin_pct

	column repeat_rate
		dataType: double
		formatString: 0.00%
		summarizeBy: average
		sourceColumn: repeat_rate

	partition segment_performance-segment_performance = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents(DataFolderPath & "segment_performance.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"customer_segment", type text},
				        {"total_revenue", type number},
				        {"total_orders", Int64.Type},
				        {"unique_customers", Int64.Type},
				        {"avg_order_value", type number},
				        {"total_margin", type number},
				        {"repeat_customers", type number},
				        {"gross_margin_pct", type number},
				        {"repeat_rate", type number}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

