table weekly_kpis

	column week_start
		dataType: dateTime
		isKey
		formatString: Short Date
		summarizeBy: none
		sourceColumn: week_start

	column total_revenue
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: total_revenue

	column total_orders
		dataType: int64
		summarizeBy: sum
		sourceColumn: total_orders

	column total_units
		dataType: int64
		summarizeBy: sum
		sourceColumn: total_units

	column total_margin
		dataType: double
		formatString: #,0.00
		summarizeBy: sum
		sourceColumn: total_margin

	column avg_order_value
		dataType: double
		formatString: #,0.00
		summarizeBy: average
		sourceColumn: avg_order_value

	column unique_customers
		dataType: int64
		summarizeBy: sum
		sourceColumn: unique_customers

	column avg_discount
		dataType: double
		formatString: 0.00%
		summarizeBy: average
		sourceColumn: avg_discount

	column visits
		dataType: int64
		summarizeBy: sum
		sourceColumn: visits

	column cart_additions
		dataType: int64
		summarizeBy: sum
		sourceColumn: cart_additions

	column completed_orders
		dataType: int64
		summarizeBy: sum
		sourceColumn: completed_orders

	column gross_margin_pct
		dataType: double
		formatString: 0.00%
		summarizeBy: average
		sourceColumn: gross_margin_pct

	column conversion_rate
		dataType: double
		formatString: 0.00%
		summarizeBy: average
		sourceColumn: conversion_rate

	column cart_abandonment_rate
		dataType: double
		formatString: 0.00%
		summarizeBy: average
		sourceColumn: cart_abandonment_rate

	column revenue_wow_growth
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: revenue_wow_growth

	column orders_wow_growth
		dataType: double
		formatString: 0.00%
		summarizeBy: none
		sourceColumn: orders_wow_growth

	column new_customers
		dataType: int64
		summarizeBy: sum
		sourceColumn: new_customers

	column repeat_customers
		dataType: int64
		summarizeBy: sum
		sourceColumn: repeat_customers

	partition weekly_kpis-weekly_kpis = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents(DataFolderPath & "weekly_kpis.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.None]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"week_start", type date},
				        {"total_revenue", type number},
				        {"total_orders", Int64.Type},
				        {"total_units", Int64.Type},
				        {"total_margin", type number},
				        {"avg_order_value", type number},
				        {"unique_customers", Int64.Type},
				        {"avg_discount", type number},
				        {"visits", Int64.Type},
				        {"cart_additions", Int64.Type},
				        {"completed_orders", Int64.Type},
				        {"gross_margin_pct", type number},
				        {"conversion_rate", type number},
				        {"cart_abandonment_rate", type number},
				        {"revenue_wow_growth", type number},
				        {"orders_wow_growth", type number},
				        {"new_customers", Int64.Type},
				        {"repeat_customers", Int64.Type}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

